/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export enum UserRole {
    USER = 'USER',
    TALLULAH_ADMIN = 'TALLULAH_ADMIN',
    FORM_INTAKE_USER = 'FORM_INTAKE_USER',
    EMAIL_INTEGRATION_USER = 'EMAIL_INTEGRATION_USER',
    CONTENT_GENERATION_USER = 'CONTENT_GENERATION_USER',
    PATIENT_PROFILE_USER = 'PATIENT_PROFILE_USER',
    ETAPESTRY_USER = 'ETAPESTRY_USER',
}